### ISSUE TITLE
Assessment Results

### ISSUE THREAD

**Issue by rwarbelow** [gregoryanderson/mod0skills#1]
# Checklist/Rubric

### Part I: Creating Directories and Files; Initializing Git and Pushing to GitHub

- [ ] I named my directories correctly. 
> This is small (`mod0skills` vs. `mod_0_skills`), but incorrect naming can mess up file path references. 
- [x] I named my files correctly.
- [x] I structured my files and directories correctly. 
- [x] I made one initial commit.
- [x] I pushed my initial commit to GitHub.

### Part II: Top Down Design

- [ ] I broke down larger processes into smaller layers.
> This is a good start, but we'd like to see another sub-layer to know that you're able to continue breaking down steps.
- [x] I added and committed my changes with a properly formatted commit message starting with a verb and a capital letter.
- [x] I pushed my changes to Github. 

### Part III: Classes, Objects, Attributes, and Methods

Class #1 Checklist
- [x] I structured and named my directories and files correctly.
- [x] The three attributes I chose for **Class #1** represent properties or characteristics.
- [ ] I identified the data type (string, integer, boolean, array, hash/object, datetime) for attributes in **Class 1**.
> `Daily_Special` should be a boolean (true/false) so that when you add objects, you can indicate whether or not the meal is a special or not. 
- [ ] The three methods I chose for **Class #1** represent behaviors or actions.
> `Change_Special` should be a method on a `Menu` class, not a `Meal` class. Otherwise, this is like asking a `Pizza` to change a `Pasta` into the daily special (which would not be the responsibility or realm of the pizza). 
- [x] I described what the methods do in **Class 1**.
- [ ] I added and committed the `class_1.txt` file **separately** with a properly formatted commit message. 
> Try to be more specific with your commit messages. Instead of `Add files`, try `Add class template for Meal` (or something like that) 

Class #1 Example Object Checklist
- [ ] The object I chose for **Class 1** is an instance of this class. 
> It seems like you're using `Pizza` as the entire category of pizza instead of an object. An object should be one very specific instance of the class. For example, if your class is `Meal`, then your specific object could be something like `Cheese Pizza` or `Hawaiian Pizza`, etc. If you're using `Pizza` generically, then it, itself, should be a class from which you can define very specific types (objects) of pizza. 
- [x] I listed the values for each attribute of this object. 
- [x] I listed the results of each method for this object. 
- [x] I added and committed the `class_1_example_object.txt` file **separately** with a properly formatted commit message. 

Class #2 Checklist
- [x] The three attributes I chose for **Class #2** represent states or characteristics.
- [x] I identified the data type (string, integer, boolean, array, hash/object, datetime) for attributes in **Class 2**.
- [x] The three methods I chose for **Class #2** represent behaviors or actions.
- [x] I described what the methods do in **Class 2**.
- [ ] I added and committed the `class_2.txt` file **separately** with a properly formatted commit message. 
> Make sure you commit your files separately. 

Class #2 Example Object Checklist
- [x] The object I chose for **Class 2** is an instance of this class. 
- [x] I listed the values for each attribute of this object. 
- [x] I listed the results of each method for this object. 
- [x] I added and committed the `class_2_example_object.txt` file **separately** with a properly formatted commit message. 
> Make sure you commit your files separately. 

### Assessment Results
- [ ] Technical Ready
- [x] Pending
> Next steps:

> 1. Add one more layer of sub-steps to your top down design file.
> 2. Create one more file called class_3.txt and define a class that you would find in a city. Be sure that the methods are all actions of/for that specific class. Create another file called class_3_example_object.txt and give the attributes and methods for a specific object of that class.
- [ ] Not Technical Ready
